//= require libs/jquery-1.7.1.min
//= require libs/sugar-1.3.6.min
//= require app/helpers
//= require app/user
//= require app/users
//= require app/room
//= require_tree ./app/components/.
//= require game/maps
//= require game/keystate
//= require game/player
//= require game/helpers
//= require game/init
// require page/index
